---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-main-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/rabbitmq

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-main-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: rabbitmq-main-data

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672 # Management console port targetPort: 15672 # Expose management console port
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq  # Keep the existing selector labels
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
              name: rabbitmq
            - containerPort: 15672
              name: rabbitmq-mgmt
          env:
            - name: RABBITMQ_MANAGEMENT
              value: "true"
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"  # Set your desired username here
            - name: RABBITMQ_DEFAULT_PASS
              value: "lT6j6MJDKfkGpZS"  # Set your desired password here
          volumeMounts:
            - name: rabbitmq-main-data
              mountPath: /var/lib/rabbitmq/
      volumes:
        - name: rabbitmq-main-data
          persistentVolumeClaim:
            claimName: rabbitmq-main-pvc
